// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9kfB6wLpvHhfNTnay6T4vDR_MjsJlRgo',
    appId: '1:907179334615:android:f778f2ca93cd13bed18992',
    messagingSenderId: '907179334615',
    projectId: 'campus-market-bfac9',
    databaseURL: 'https://campus-market-bfac9-default-rtdb.firebaseio.com',
    storageBucket: 'campus-market-bfac9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlSMVV5_Sq3ZbrKGmZStDYv050yB6aZiM',
    appId: '1:907179334615:ios:1b7837b310a82adbd18992',
    messagingSenderId: '907179334615',
    projectId: 'campus-market-bfac9',
    databaseURL: 'https://campus-market-bfac9-default-rtdb.firebaseio.com',
    storageBucket: 'campus-market-bfac9.appspot.com',
    androidClientId: '907179334615-a3s2n10h3qareq4c5smta1n50okqgq74.apps.googleusercontent.com',
    iosClientId: '907179334615-b13fg0iq2udu4uqjbqq3f0pt4tfmse68.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusMarket',
  );
}
